# Generated by Django 5.0.2 on 2024-03-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundit', '0003_spotifytoken_youtubetoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='connected_account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='youtubetoken',
            old_name='connected_account',
            new_name='user',
        ),
    ]
