# Generated by Django 5.0.2 on 2024-03-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundit', '0004_rename_connected_account_spotifytoken_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='expires_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='youtubetoken',
            name='expires_in',
            field=models.DateTimeField(),
        ),
    ]
