# Generated by Django 5.0.2 on 2024-03-23 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundit', '0005_alter_spotifytoken_expires_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='youtubetoken',
            name='user',
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spotify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='youtubetoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube', to=settings.AUTH_USER_MODEL),
        ),
    ]
