# Generated by Django 5.0.2 on 2024-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundit', '0006_remove_spotifytoken_user_remove_youtubetoken_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubetoken',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
