# Generated by Django 5.0.2 on 2024-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundit', '0007_alter_youtubetoken_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfered_playlists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='transfered_tacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubetoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
