# Generated by Django 5.0.2 on 2024-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundit', '0008_user_transfered_playlists_user_transfered_tacks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfered_tracks', models.IntegerField(default=0)),
                ('transfered_playlists', models.IntegerField(default=0)),
                ('deleted_playlists', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='transfered_tacks',
            new_name='transfered_tracks',
        ),
    ]
