# Generated by Django 5.0.2 on 2024-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundit', '0010_user_deleted_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubetoken',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
